name: Check Version Route

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21" # Update with the latest stable Go version

      - name: Install dependencies
        run: go mod tidy

      - name: Build the application
        run: make build

      - name: Install jq (for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Run the application in the background
        run: ./bin/main &
        env:
          PORT: 8080 # Set the port if configurable by the application

      - name: Wait for application to start
        run: sleep 5

      - name: Check the /version route
        run: |
          response=$(curl -s http://localhost:8080/version)
          version=$(echo $response | jq -r .version)
          if [ -z "$version" ]; then
            echo "Error: Version is empty or not found"
            exit 1
          fi
          echo "Version returned: $version"

      - name: Cleanup background process
        run: |
          pkill -f ./bin/main || echo "Application already stopped"
