name: Docker Image Build CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/hivebox-api:${{ github.event.ref }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/hivebox-api:${{ github.event.ref }}
   